#!/bin/zsh
set -u

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE_DIR="$PROJECT_ROOT/.state"
LOG_FILE="$STATE_DIR/status_server.log"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_ROOT/.venv/bin/python}"

if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="$(command -v python3 || command -v python)"
fi

mkdir -p "$STATE_DIR"
cd "$PROJECT_ROOT" || exit 78

echo "$(date -u '+%Y-%m-%dT%H:%M:%SZ') starting rebalancing.status_server" >>"$LOG_FILE"

exec env \
  PYTHONPATH="$PROJECT_ROOT/src" \
  ENGINE_HOST="127.0.0.1" \
  ENGINE_PORT="8788" \
  ENGINE_CORS_ORIGIN="*" \
  ENGINE_WEBHOOK_TOKEN_FILE="$STATE_DIR/engine_webhook_token" \
  ENGINE_SIGNAL_STORE_PATH="$STATE_DIR/tradingview_alerts.json" \
  ENGINE_SIGNAL_STORE_MAX_RECORDS="200" \
  ENGINE_STATUS_ALERT_EVENT_LIMIT="200" \
  ENGINE_TV_MAX_ALERT_AGE_SECONDS="0" \
  ENGINE_TV_ALLOW_PROBE_ENTRIES="true" \
  ENGINE_TV_PROBE_LEVERAGE="0.5" \
  PAPER_TRADING_ENABLED="true" \
  PAPER_INITIAL_EQUITY="1000" \
  PAPER_STATE_PATH="$STATE_DIR/paper_trading.json" \
  PAPER_MAX_LEVERAGE="2" \
  PAPER_MIN_ORDER_NOTIONAL="10" \
  PAPER_MIN_REBALANCE_MINUTES="60" \
  PAPER_BLOCK_NEW_ENTRIES_LOSS_PCT="-1.0" \
  PAPER_FEE_RATE="0.0004" \
  PAPER_SLIPPAGE_BPS="0" \
  PAPER_TRADE_HISTORY_LIMIT="500" \
  FALLBACK_EQUITY="1000" \
  FALLBACK_WALLET_BALANCE="1000" \
  DAY_START_EQUITY="1000" \
  WEEK_START_EQUITY="1000" \
  MONTH_START_EQUITY="1000" \
  BINANCE_LIVE_TRADING="false" \
  BINANCE_ENABLE_ORDERS="false" \
  BINANCE_POSITION_MODE="ONE_WAY" \
  MARKET_INTERNALS_CACHE_SECONDS="300" \
  MARKET_INTERNALS_UNIVERSE_LIMIT="200" \
  MARKET_INTERNALS_BREADTH_LIMIT="100" \
  MARKET_INTERNALS_BREADTH_WORKERS="8" \
  "$PYTHON_BIN" -m rebalancing.status_server
